name: Build and deploy full-stack app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          CI=false npm run build  # Build React app

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Prepare deployment package
        run: |
          # Create deployment directory
          mkdir deployment
          
          # Copy backend files
          cp -r backend/* deployment/
          
          # Create public folder and copy built frontend
          mkdir -p deployment/public
          cp -r frontend/build/* deployment/public/
          
          # Clean up
          rm -rf deployment/node_modules

      - name: Zip artifact for deployment
        run: |
          cd deployment
          zip -r ../release.zip . -x '*.git*'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: fullstack-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: fullstack-app

      - name: Unzip artifact
        run: unzip release.zip -d deployment-folder

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B21E5E4DFE134BC6B291BBE504861356 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_119CA0B556034DA6BFA1C69A804B5276 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_95EB0CA4B2CD45ABA4EE0F12CE923D58 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PoseidonsNotebook'
          slot-name: 'Production'
          package: deployment-folder
