name: Build and deploy Node.js app to Azure Web App - PoseidonsNotebook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install and build backend
        run: |
          cd backend
          npm install
          npm run build --if-present
          # npm run test --if-present  # Uncomment if you have tests

      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build --if-present
          # npm run test --if-present  # Uncomment if you have tests

      - name: Prepare deployment package
        run: |
          # Create a deployment directory
          mkdir deployment
          
          # Copy backend files (assuming your Azure app runs the backend)
          cp -r backend/* deployment/
          
          # If you need to serve frontend from backend, copy built frontend files to backend public folder
          # mkdir deployment/public
          # cp -r frontend/dist/* deployment/public/  # Adjust 'dist' to your frontend build folder name
          
          # Remove node_modules to avoid including them (they'll be installed on Azure)
          rm -rf deployment/node_modules

      - name: Zip artifact for deployment
        run: |
          cd deployment
          zip -r ../release.zip . -x '*.git*'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip -d deployment-folder

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B21E5E4DFE134BC6B291BBE504861356 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_119CA0B556034DA6BFA1C69A804B5276 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_95EB0CA4B2CD45ABA4EE0F12CE923D58 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PoseidonsNotebook'
          slot-name: 'Production'
          package: deployment-folder
          
